apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      securityContext:
        fsGroup: 101
        fsGroupChangePolicy: "Always"

      containers:
        - name: clickhouse
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 9000
            - containerPort: 8123
          
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse
            - name: logs
              mountPath: /var/log/clickhouse-server
            - name: config
              mountPath: /etc/clickhouse-server/config.d/z-overrides.xml
              subPath: z-overrides.xml
            - name: users
              mountPath: /etc/clickhouse-server/users.d/custom.xml
              subPath: users.xml

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: config
          configMap:
            name: clickhouse-config
        - name: users
          configMap:
            name: clickhouse-users
        - name: logs
          emptyDir: {}

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.storage.className | quote }}
        resources:
          requests:
            storage: {{ .Values.storage.size | quote }}
