apiVersion: batch/v1
kind: CronJob
metadata:
  name: clickhouse-backup
spec:
  schedule: "{{ .Values.backup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: altinity/clickhouse-backup:latest
              env:
                - name: S3_ENDPOINT
                  value: {{ .Values.backup.endpoint }}
                - name: S3_BUCKET
                  value: {{ .Values.backup.bucket }}
              command:
                - /bin/sh
                - -c
                - |
                  clickhouse-backup create && clickhouse-backup upload
          restartPolicy: OnFailure
