apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-users
data:
  users.xml: |
    <clickhouse>
      <profiles>
        <default>
          <max_memory_usage>1000000000</max_memory_usage>
          <max_threads>{{ .Values.clickhouse.maxThreads }}</max_threads>
        </default>
      </profiles>
      <users>
        <{{ .Values.clickhouse.user }}>
          <password>{{ .Values.clickhouse.password }}</password>
          <networks>
            <ip>::/0</ip>
          </networks>
          <profile>default</profile>
        </{{ .Values.clickhouse.user }}>
      </users>
    </clickhouse>
